name: example
description: Demonstrates how to use the jpush plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  fl_jpush:
    path: ../
  flutter_curiosity: ^4.0.1
  fl_jpush_android:
    path: ../../fl_jpush_android
  #  fl_jpush_android_fcm: ^0.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true