name: example
description: Demonstrates how to use the jpush plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  fl_jpush:
    path: ../
  fl_jpush_android:
    path: ../../fl_jpush_android
  fl_jpush_android_fcm:
    path: ../../fl_jpush_android_fcm
  flutter:
    sdk: flutter
  flutter_curiosity: ^3.5.1

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true