name: fl_jverify
description: Jverify plugin for flutter, only Android and IOS are supported
version: 0.1.1
repository: https://github.com/Wayaer/fl_jverify.git

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: fl.jverify
        pluginClass: FlJVerifyPlugin
      ios:
        pluginClass: FlJVerifyPlugin