name: fl_jpush_android_fcm
description: JPush integrated vendor push channel,Valid only on Android devices
version: 4.0.0
repository: https://github.com/Wayaer/fl_jpush/tree/main/fl_jpush_android_fcm

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: fl.jpush.android.fcm
        pluginClass: FlJPushAndroidFCMPlugin
