name: example
description: Demonstrates how to use the jpush plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  fl_jpush:
    path: ../
  flutter_curiosity: ^5.0.3
  fl_jpush_android:
    path: ../../fl_jpush_android
  #  fl_jpush_android_fcm:
  #    path: ../../fl_jpush_android_fcm
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true