name: example
description: Demonstrates how to use the jpush plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter_curiosity: ^6.1.0
  fl_extended: ^1.1.2
  fl_jpush:
    path: ../
  #  fl_jpush_android:
  #    path: ../../fl_jpush_android
  #  fl_jpush_android_fcm:
  #    path: ../../fl_jpush_android_fcm
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true