name: fl_jpush
description: jpush plugin for flutter, only Android and IOS are supported
version: 3.3.0+1
repository: https://github.com/Wayaer/fl_jpush/tree/main/fl_jpush

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: fl.jpush
        pluginClass: JPushPlugin
      ios:
        pluginClass: JPushPlugin
