name: example
description: Demonstrates how to use the fl_jverify plugin.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_jverify:
    path: ../
  flutter_curiosity: ^4.0.1
  flutter_waya: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true