name: example
description: Demonstrates how to use the fl_jverify plugin.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_jverify:
    path: ../
  flutter_curiosity: 6.3.1
  fl_extended: ^1.5.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true