name: example
description: Demonstrates how to use the fl_jpush_android_fcm plugin.
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_jpush:
    path: ../../fl_jpush
  fl_jpush_android_fcm:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
